### PR TITLE
Add tooling

### PR DESCRIPTION
**Pull request by pythoninthegrass**
- vscode (devcontainer, debug configs)
- github (dependabot, funding, issue template)
- django (update doc urls, allow localhost)
- docker (gunicorn/uvicorn, nginx, postgres)
- editorconfig (auto formatting locally)
- gitignore (generated comprehensive python exclusions)
- shellcheckrc (lint shell scripts w/exclusions)
- tool-versions (asdf)
- unlicense
- poetry (venv, deps, packaging)
- startup.sh (run server after extensive scaffolding w/error handling)

### CODE REVIEW

**Comment by pythoninthegrass** [comment]
Feel free to cherry pick what you'd find useful. I'm especially proud of `startup.sh` and the nginx portion for static files.

Probably has some corner cases/bugs but I've yet to implement [bats](https://opensource.com/article/19/2/testing-bash-bats) hahaha

**Comment by zchtodd** [comment]
Hi @pythoninthegrass, wow, thanks for the big contribution to the project.  I think Dockerizing the project and adding a Compose file makes sense.  I don't know how much future development this project will receive, but I'm happy to merge your branch.

I did notice that the main `Dockerfile` seems to have a lot of dev dependencies pulled into it.  If you could make that a bit more minimal I think we'd be good to merge if you'd like.

**Comment by pythoninthegrass** [comment]
Sure! Can split the devcontainer from the main one and golf any extra deps
________________________________

**Comment by pythoninthegrass** [comment]
Was able to shrink the image on the runner portion from 346 MB to 258 MB according to [dive](https://www.docker.com/blog/reduce-your-image-size-with-the-dive-in-docker-extension/).

Let me know if you need anything else 👌

**Pull request merged**
